### ISSUE TITLE
Quick review

### ISSUE THREAD

**Issue by gaydabura** [skilld-labs/skilld-varnish#1]
1. https://github.com/skilld-labs/skilld-varnish/blob/master/4.1/Dockerfile#L3 Enviroment varibales need to be configurable 
2. https://github.com/skilld-labs/skilld-varnish/blob/master/4.1/default.vcl#L14 IP is hardcoded, i guess its typo error
3. vcl file to be checked with https://www.drupal.org/docs/7/caching-to-improve-performance/varnish-4x-configuration and https://www.varnish-software.com/wiki/content/tutorials/drupal/drupal_vcl.html  and https://github.com/NITEMAN/varnish-bites aswell (source)

**Comment by andypost** [comment]
Do not assign to me things you did not read
- https://www.drupal.org/docs/8/api/cache-api/cache-tags-varnish
- https://www.jeffgeerling.com/blog/2016/use-drupal-8-cache-tags-varnish-and-purge

This is a common image that contains all you need to run d8
